name: autoclose_bloc
description: autoclose_bloc is a package providing AutoClose functionality for the Bloc
version: 1.0.1
repository: https://github.com/vlastachu/autoclose
issue_tracker: https://github.com/vlastachu/autoclose/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  autoclose: ^1.0.1

dependency_overrides:
  autoclose:
    path: ../..

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
